### ISSUE TITLE
Distribution isn't split evenly

### ISSUE THREAD

**Issue by Dragonzroar** [safemoonprotocol/Safemoon.sol#59]
I've gained around 50,000 safemoon from when I've started but others that have joined later then me have already gained 100,000+. All the people I've talked with about their gains use Trust Wallet and so do I. Is there an issue with the distributions?

**Comment by Jovonni** [comment]
It’s weighted based on how many tokens your address holds

Do they have the same amount as you?

**Comment by Dragonzroar** [comment]
No, they have more than me. I couldn't find anything that stated that on their website so I was confused. Thanks for letting me know
